[package]
name = "img2txt"
version = "0.1.0"
authors = ["Bernardozomer <Bernardo.Barzotto@edu.pucrs.br>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
image = "0.23"
